# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MojoX-UserAgent
version:      0.21
version_from: lib/MojoX/UserAgent.pm
installdirs:  site
requires:
    Mojo:                          0.991250
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
